


import '../Learning/Learn_Abc/model/abc_model.dart';

List <Abc> abcd=[
  Abc(
    image: 'images/abc/abc/a.png',
    pronounce: 'a',
    f1image: 'images/abc/abc_shapes/ant.png',
    f1name:'Ant',
    f2image: 'images/abc/abc_shapes/apple.png',
    f2name: 'Apple',
    pronounce_f2name:  'a p p l e apple',
    pronounce_f1name: 'A N T ant',
  ),
  Abc(
    image: 'images/abc/abc/b.png',
    pronounce: 'b',
    f1image: 'images/abc/abc_shapes/ball.png',
    f1name:'Ball',
    f2image: 'images/abc/abc_shapes/butterfly.png',
    f2name: 'Butterfly',
    pronounce_f1name:  'B A L L ball',
    pronounce_f2name: 'B U T T E R F L Y butterfly',
  ),
  Abc(
    image: 'images/abc/abc/c.png',
    pronounce: 'c',
    f1image: 'images/abc/abc_shapes/cat.png',
    f1name:'Cat',
    f2image: 'images/abc/abc_shapes/cow.png',
    f2name: 'Cow',
    pronounce_f1name:  'C A T cat',
    pronounce_f2name: 'C O W cow',
  ),
  Abc(
    image: 'images/abc/abc/d.png',
    pronounce: 'd',
    f1image: 'images/abc/abc_shapes/dog.png',
    f1name:'Dog',
    f2image: 'images/abc/abc_shapes/duck.png',
    f2name: 'Duck',
    pronounce_f1name:  'D O G dog',
    pronounce_f2name: 'D U C K duck',
  ),
  Abc(
    image: 'images/abc/abc/e.png',
    pronounce: 'e',
    f1image: 'images/abc/abc_shapes/elephant.png',
    f1name:'Elephant',
    f2image: 'images/abc/abc_shapes/ear.png',
    f2name: 'Ear',
    pronounce_f1name:  'E L E P H A N T elephant',
    pronounce_f2name: 'E A R ear',
  ),
  Abc(
    image: 'images/abc/abc/f.png',
    pronounce: 'f',
    f1image: 'images/abc/abc_shapes/fan.png',
    f1name:'Fan',
    f2image: 'images/abc/abc_shapes/fish.png',
    f2name: 'Fish',
    pronounce_f1name:  'F A N fan',
    pronounce_f2name: 'F I S H fish',
  ),
  Abc(
    image: 'images/abc/abc/g.png',
    pronounce: 'g',
    f1image: 'images/abc/abc_shapes/gouva.png',
    f1name:'Guava',
    f2image: 'images/abc/abc_shapes/grapes.png',
    f2name: 'Grapes',
    pronounce_f1name:  'G U A V A guava',
    pronounce_f2name: 'G R A P E S grapes',
  ),
  Abc(
    image: 'images/abc/abc/h.png',
    pronounce: 'h',
    f1image: 'images/abc/abc_shapes/hat.png',
    f1name:'Hat',
    f2image: 'images/abc/abc_shapes/house.png',
    f2name: 'House',
    pronounce_f1name:  'H A T hat',
    pronounce_f2name: 'H O U S E house',
  ),
  Abc(
    image: 'images/abc/abc/i.png',
    pronounce: 'i',
    f1image: 'images/abc/abc_shapes/ice_cream.png',
    f1name:'Ice cream',
    f2image: 'images/abc/abc_shapes/iron.png',
    f2name: 'Iron',
    pronounce_f1name:  'I C E C R E A  M ice cream',
    pronounce_f2name: 'I R O N iron',
  ),
  Abc(
    image: 'images/abc/abc/j.png',
    pronounce: 'j',
    f1image: 'images/abc/abc_shapes/jacket.png',
    f1name:'Jacket',
    f2image: 'images/abc/abc_shapes/jar.png',
    f2name: 'Jar',
    pronounce_f1name:  'J A C K E T jacket',
    pronounce_f2name: 'J A R jar',
  ),
  Abc(
    image: 'images/abc/abc/k.png',
    pronounce: 'k',
    f1image: 'images/abc/abc_shapes/kite.png',
    f1name:'Kite',
    f2image: 'images/abc/abc_shapes/key.png',
    f2name: 'Key',
    pronounce_f2name:  'K E Y key',
    pronounce_f1name: 'K I T E KITE',
  ),
  Abc(
    image: 'images/abc/abc/l.png',
    pronounce: 'l',
    f1image: 'images/abc/abc_shapes/lion.png',
    f1name:'Lion',
    f2image: 'images/abc/abc_shapes/lamp.png',
    f2name: 'Lamp',
    pronounce_f2name:  'L A M P lamp',
    pronounce_f1name: 'L I O N lion',
  ), Abc(
    image: 'images/abc/abc/m.png',
    pronounce: 'm',
    f1image: 'images/abc/abc_shapes/monkey.png',
    f1name:'Monkey',
    f2image: 'images/abc/abc_shapes/mango.png',
    f2name: 'Mango',
    pronounce_f2name:  'M A N G O mango',
    pronounce_f1name: 'M O N K E Y monkey',
  ),
  Abc(
    image: 'images/abc/abc/n.png',
    pronounce: 'n',
    f1image: 'images/abc/abc_shapes/nose.png',
    f1name:'Nose',
    f2image: 'images/abc/abc_shapes/nest.png',
    f2name: 'Nest',
    pronounce_f2name:  'N E S T nest',
    pronounce_f1name: 'N O S E nose',
  ),
  Abc(
    image: 'images/abc/abc/o.png',
    pronounce: 'o',
    f1image: 'images/abc/abc_shapes/owl.png',
    f1name:'Owl',
    f2image: 'images/abc/abc_shapes/orange.png',
    f2name: 'Orange',
    pronounce_f2name:  'O R A N G E orange',
    pronounce_f1name: 'O W L owl',
  ),
  Abc(
    image: 'images/abc/abc/p.png',
    pronounce: 'p',
    f1image: 'images/abc/abc_shapes/plane.png',
    f1name:'Plane',
    f2image: 'images/abc/abc_shapes/pen.png',
    f2name: 'Pen',
    pronounce_f2name:  'P E N pen',
    pronounce_f1name: 'P L A N E plane',
  ),
  Abc(
    image: 'images/abc/abc/q.png',
    pronounce: 'q',
    f1image: 'images/abc/abc_shapes/quill.png',
    f1name:'Quill',
    f2image: 'images/abc/abc_shapes/queen.png',
    f2name: 'Queen',
    pronounce_f2name:  'Q U E E N queen',
    pronounce_f1name: 'Q U I L L quill',
  ),
  Abc(
    image: 'images/abc/abc/r.png',
    pronounce: 'r',
    f1image: 'images/abc/abc_shapes/rose.png',
    f1name:'Rose',
    f2image: 'images/abc/abc_shapes/ring.png',
    f2name: 'Ring',
    pronounce_f2name:  'R I N G RING',
    pronounce_f1name: 'R O S E ROSE',
  ), Abc(
    image: 'images/abc/abc/s.png',
    pronounce: 's',
    f1image: 'images/abc/abc_shapes/sun.png',
    f1name:'Sun',
    f2image: 'images/abc/abc_shapes/shoes.png',
    f2name: 'Shoes',
    pronounce_f2name:  'S H O E S shoes',
    pronounce_f1name: 'S U N sun',
  ), Abc(
    image: 'images/abc/abc/t.png',
    pronounce: 't',
    f1image: 'images/abc/abc_shapes/tiger.png',
    f1name:'Tiger',
    f2image: 'images/abc/abc_shapes/tree.png',
    f2name: 'Tree',
    pronounce_f2name:  'T R E E tree',
    pronounce_f1name: 'T I G E R tiger',
  ),
  Abc(
    image: 'images/abc/abc/u.png',
    pronounce: 'u',
    f1image: 'images/abc/abc_shapes/unicorn.png',
    f1name:'Unicorn',
    f2image: 'images/abc/abc_shapes/umbrella.png',
    f2name: 'Umbrella',
    pronounce_f2name:  'U M B R E L L A umbrella',
    pronounce_f1name: 'U N I C O R N unicorn',
  ),
  Abc(
    image: 'images/abc/abc/v.png',
    pronounce: 'v',
    f1image: 'images/abc/abc_shapes/van.png',
    f1name:'Van',
    f2image: 'images/abc/abc_shapes/violin.png',
    f2name: 'Violin',
    pronounce_f2name:  'V I O L I N violin',
    pronounce_f1name: 'V A N VAN',
  ),
  Abc(
    image: 'images/abc/abc/w.png',
    pronounce: 'w',
    f1image: 'images/abc/abc_shapes/wheel.png',
    f1name:'Wheel',
    f2image: 'images/abc/abc_shapes/window.png',
    f2name: 'Window',
    pronounce_f2name:  'W I N D O W window',
    pronounce_f1name: 'W H E E L wheel',
  ),
  Abc(
    image: 'images/abc/abc/x.png',
    pronounce: 'x',
    f1image: 'images/abc/abc_shapes/x_ray.png',
    f1name:'X ray',
    f2image: 'images/abc/abc_shapes/xylophone.png',
    f2name: 'Xylophone',
    pronounce_f2name:  'X Y L O P H O N E xylophone',
    pronounce_f1name: 'X R A Y x ray',
  ),
  Abc(
    image: 'images/abc/abc/y.png',
    pronounce: 'y',
    f1image: 'images/abc/abc_shapes/yak.png',
    f1name:'Yak',
    f2image: 'images/abc/abc_shapes/yoyo.png',
    f2name: 'Yoyo',
    pronounce_f2name:  'Y O Y O yoyo',
    pronounce_f1name: 'Y A K yak',
  ),
  Abc(
    image: 'images/abc/abc/z.png',
    pronounce: 'z',
    f1image: 'images/abc/abc_shapes/zebra.png',
    f1name:'Zebra',
    f2image: 'images/abc/abc_shapes/zip.png',
    f2name: 'Zip',
    pronounce_f2name:  'Z I p zip',
    pronounce_f1name: 'Z E B R A zebra',
  ),



];
