import '../Quiz/model/question_model.dart';

List<Questions> fruits = [
  Questions(
      questionImage: 'images/fruits/apple.png',
      ans: 'Apple',
      op1: 'Pineapple',
      op2: 'Apple',
      op3: 'Grapes',
      op4: 'Melon',
      selected: ''),
  Questions(
      questionImage: 'images/fruits/bnanna.png',
      ans: 'Banana',
      op1: 'Banana',
      op2: 'Coconut',
      op3: 'Apple',
      op4: 'Watermelon',
      selected: ''),
  Questions(
      questionImage: 'images/fruits/coconut.png',
      ans: 'Coconut',
      op1: 'Pineapple',
      op2: 'Apple',
      op3: 'Coconut',
      op4: 'Banana',
      selected: ''),
  Questions(
      questionImage: 'images/fruits/gouva.png',
      ans: 'Guava',
      op1: 'Lemon',
      op2: 'Guava',
      op3: 'Mango',
      op4: 'Melon',
      selected: ''),
  Questions(
      questionImage: 'images/fruits/grapes.png',
      ans: 'Grapes',
      op1: 'Pomegranate',
      op2: 'Apple',
      op3: 'Banana',
      op4: 'Grapes',
      selected: ''),
  Questions(
      questionImage: 'images/fruits/mango.png',
      ans: 'Mango',
      op1: 'Mango',
      op2: 'Melon',
      op3: 'Watermelon',
      op4: 'Banana',
      selected: ''),
  Questions(
      questionImage: 'images/fruits/orange.png',
      ans: 'Orange',
      op1: 'Guava',
      op2: 'Orange',
      op3: 'Coconut',
      op4: 'Apple',
      selected: ''),
  Questions(
      questionImage: 'images/fruits/permagrent.png',
      ans: 'Pomegranate',
      op1: 'Melon',
      op2: 'Apple',
      op3: 'Pomegranate',
      op4: 'Orange',
      selected: ''),
  Questions(
      questionImage: 'images/fruits/pineapple.png',
      ans: 'Pineapple',
      op1: 'Apple',
      op2: 'Pineapple',
      op3: 'Coconut',
      op4: 'Melon',
      selected: ''),
  Questions(
      questionImage: 'images/fruits/watermelon.png',
      ans: 'Watermelon',
      op1: 'Banana',
      op2: 'Coconut',
      op3: 'Watermelon',
      op4: 'Mango',
      selected: ''),
];
List<Questions> animals = [
  Questions(
      questionImage: 'images/animals/cat.png',
      ans: 'Cat',
      op1: 'Cat',
      op2: 'Fox',
      op3: 'Tiger',
      op4: 'Camel',
      selected: ''),
  Questions(
      questionImage: 'images/animals/cow.png',
      ans: 'Cow',
      op1: 'Wolf',
      op2: 'Deer',
      op3: 'Cow',
      op4: 'Panda',
      selected: ''),
  Questions(
      questionImage: 'images/animals/crocodile.png',
      ans: 'Crocodile',
      op1: 'Monkey',
      op2: 'Crocodile',
      op3: 'Gorilla',
      op4: 'Raccoon',
      selected: ''),
  Questions(
      questionImage: 'images/animals/deer.png',
      ans: 'Deer',
      op1: 'Leopard',
      op2: 'Goat',
      op3: 'Koala',
      op4: 'Deer',
      selected: ''),
  Questions(
      questionImage: 'images/animals/dog.png',
      ans: 'Dog',
      op1: 'Fox',
      op2: 'Owl',
      op3: 'Dog',
      op4: 'Zebra',
      selected: ''),
  Questions(
      questionImage: 'images/animals/elephant.png',
      ans: 'Elephant',
      op1: 'Elephant',
      op2: 'Mole',
      op3: 'Rat',
      op4: 'Bison',
      selected: ''),
  Questions(
      questionImage: 'images/animals/giraffe.png',
      ans: 'Giraffe',
      op1: 'Horse',
      op2: 'Giraffe',
      op3: 'Squirrel',
      op4: 'Sheep',
      selected: ''),
  Questions(
      questionImage: 'images/animals/lion.png',
      ans: 'Lion',
      op1: 'Lion',
      op2: 'Fox',
      op3: 'Mouse',
      op4: 'Wolf',
      selected: ''),
  Questions(
      questionImage: 'images/animals/monkey.png',
      ans: 'Monkey',
      op1: 'Raccoon',
      op2: 'Kangaroo',
      op3: 'Mole',
      op4: 'Monkey',
      selected: ''),
  Questions(
      questionImage: 'images/animals/panda.png',
      ans: 'Panda',
      op1: 'Owl',
      op2: 'Panda',
      op3: 'Otter',
      op4: 'Rabbit',
      selected: ''),
];
List<Questions> vegetable = [
  Questions(
      questionImage: 'images/vegetables/tomato.png',
      ans: 'Tomato',
      op1: 'Potato',
      op2: 'Tomato',
      op3: 'Brinjal',
      op4: 'Radish',
      selected: ''),
  Questions(
      questionImage: 'images/vegetables/carrot.png',
      ans: 'Carrot',
      op1: 'Onion',
      op2: 'Garlic',
      op3: 'Lady Finger',
      op4: 'Carrot',
      selected: ''),
  Questions(
      questionImage: 'images/vegetables/caulifower.png',
      ans: 'Cauliflower',
      op1: 'Cauliflower',
      op2: 'Pumpkin',
      op3: 'Ginger',
      op4: 'Chilli',
      selected: ''),
  Questions(
      questionImage: 'images/vegetables/chilli.png',
      ans: 'Chilli',
      op1: 'Carrot',
      op2: 'Chilli',
      op3: 'Capsicum',
      op4: 'Spinach',
      selected: ''),
  Questions(
      questionImage: 'images/vegetables/cocumber.png',
      ans: 'Cucumber',
      op1: 'Jack Fruit',
      op2: 'Brinjal',
      op3: 'Mushroom',
      op4: 'Cucumber',
      selected: ''),
  Questions(
      questionImage: 'images/vegetables/ladyfinger.png',
      ans: 'Lady Finger',
      op1: 'Broccoli',
      op2: 'Ginger',
      op3: 'Lady Finger',
      op4: 'Radish',
      selected: ''),
  Questions(
      questionImage: 'images/vegetables/onion.png',
      ans: 'Onion',
      op1: 'Onion',
      op2: 'Potato',
      op3: 'Tomato',
      op4: 'Chilli',
      selected: ''),
  Questions(
      questionImage: 'images/vegetables/potato.png',
      ans: 'Potato',
      op1: 'Spinach',
      op2: 'Capsicum',
      op3: 'Mushroom',
      op4: 'Potato',
      selected: ''),
  Questions(
      questionImage: 'images/vegetables/pumpkin.png',
      ans: 'Pumpkin',
      op1: 'Radish',
      op2: 'Pumpkin',
      op3: 'Beetroot',
      op4: 'Asparagus',
      selected: ''),
  Questions(
      questionImage: 'images/vegetables/sweetpotato.png',
      ans: 'Sweet potato',
      op1: 'Chilli',
      op2: 'Tomato',
      op3: 'Sweet potato',
      op4: 'Garlic',
      selected: ''),
];
List<Questions> body_parts = [
  Questions(
      questionImage: 'images/body_parts/arm.png',
      ans: 'Arm',
      op1: 'Toe nail',
      op2: 'Heel',
      op3: 'Arm',
      op4: 'Stomach',
      selected: ''),
  Questions(
      questionImage: 'images/body_parts/eyes.png',
      ans: 'Eyes',
      op1: 'Eyes',
      op2: 'Finger',
      op3: 'Hand',
      op4: 'Elbow',
      selected: ''),
  Questions(
      questionImage: 'images/body_parts/finger.png',
      ans: 'Finger',
      op1: 'Neck',
      op2: 'Mouth',
      op3: 'Ear',
      op4: 'Finger',
      selected: ''),
  Questions(
      questionImage: 'images/body_parts/foot.png',
      ans: 'Foot',
      op1: 'Head',
      op2: 'Foot',
      op3: 'Hair',
      op4: 'Cheek',
      selected: ''),
  Questions(
      questionImage: 'images/body_parts/hair.png',
      ans: 'Hair',
      op1: 'Hair',
      op2: 'Nose',
      op3: 'Jaw',
      op4: 'Shoulder',
      selected: ''),
  Questions(
      questionImage: 'images/body_parts/hand.png',
      ans: 'Hand',
      op1: 'Chest',
      op2: 'Hand',
      op3: 'Arm',
      op4: 'Knee',
      selected: ''),
  Questions(
      questionImage: 'images/body_parts/leg.png',
      ans: 'Leg',
      op1: 'Knee',
      op2: 'Foot',
      op3: 'Leg',
      op4: 'Toe',
      selected: ''),
  Questions(
      questionImage: 'images/body_parts/lips.png',
      ans: 'Lips',
      op1: 'Ear',
      op2: 'Eye',
      op3: 'Finger',
      op4: 'Lips',
      selected: ''),
  Questions(
      questionImage: 'images/body_parts/nose.png',
      ans: 'Nose',
      op1: 'Stomach',
      op2: 'Nose',
      op3: 'Neck',
      op4: 'Hair',
      selected: ''),
  Questions(
      questionImage: 'images/body_parts/teeth.png',
      ans: 'Teeth',
      op1: 'Teeth',
      op2: 'Head',
      op3: 'Elbow',
      op4: 'Cheek',
      selected: ''),
];